### ISSUE TITLE
Support arm64

### ISSUE THREAD

**Issue by rverma-nsl** [aws/secrets-store-csi-driver-provider-aws#10]
Prefer multi arch builds using buildx

**Comment by joebaro** [comment]
Thank you for your feedback. We have noted this as a feature request.

**Comment by mohandass-pat** [comment]
Hi, any update on this one?

**Comment by gbhosal** [comment]
I'm also waiting for this feature. Any update on this?

**Comment by rverma-nsl** [comment]
Feel free to use docker pull ghcr.io/nslhb/secrets-store-csi-driver-provider-aws:latest, while this came in mainline.

**Comment by lpmatos** [comment]
@rverma-nsl thx!
