### ISSUE TITLE
Secrets Store CSI Driver Not working on a fully private eks cluster

### ISSUE THREAD

**Issue by gurudath** [aws/secrets-store-csi-driver-provider-aws#107]
**Describe the bug**
If we are using a fully private eks cluster, the secret is not getting mounted under /var/lib/kubelet/pods/959371fb-624f-4c38-8897-0ae8666f1711/volumes/kubernetes.io~csi/secrets-store-inline/mount, and giving  failed to mount secrets store object content 

But this works fine when it's not a fully private cluster and pulls the images from the public repo as in the helm chart. Validated it

**To Reproduce**
followed the same step as in https://github.com/aws/secrets-store-csi-driver-provider-aws, but of the fully private cluster but all images are pulled from ECR

1. Push all the images to ECR and the secrets-store-csi-driver-provider-aws image was generated using the commands under private-installer.yaml
 `*****************.dkr.ecr.*******.amazonaws.com/csi-node-driver-registrar:v2.5.1
*****************.dkr.ecr.*******.amazonaws.com/driver:v1.2.2
*****************.dkr.ecr.*******.amazonaws.com/driver-crds:v1.2.2
*****************.dkr.ecr.*******.amazonaws.com/livenessprobe:v2.7.0
*****************.dkr.ecr.*******.amazonaws.com/metrics-server:v0.6.1
*****************.dkr.ecr.*******.amazonaws.com/secrets-store-csi-driver-provider-aws:latest
`
2. Installed csr driver using below `helm upgrade --install csi-secrets-store secrets-store-csi-driver/secrets-store-csi-driver -n kube-system --set grpcSupportedProviders="aws"  --set syncSecret.enabled=true --set enableSecretRotation=false --set linux.image.repository=*******.dkr.ecr.*******.amazonaws.com/driver --set linux.image.tag=v1.2.2 --set linux.crds.image.repository=*******.dkr.ecr.*******.amazonaws.com/driver-crds --set linux.crds.image.tag=v1.2.2 --set linux.registrarImage.repository=*******.dkr.ecr.*******.amazonaws.com/csi-node-driver-registrar --set linux.registrarImage.tag=v2.5.1 --set linux.livenessProbeImage.repository=*******.dkr.ecr.*******.amazonaws.com/livenessprobe --set linux.livenessProbeImage.tag=v2.7.0`
3. Then run `envsubst < deployment/private-installer.yaml | kubectl apply -f -`
4. Later deploy the secret provider class and pods as shown in README.md file 

NOTE: Service account, secrets and OIDC all had required  permission

Do you also notice this bug when using a different secrets store provider (Vault/Azure/GCP...)? **No(Didn't try)**

**Expected behavior**
The secret should be mounted and will be available as env variable

**Environment:**
OS => Amazon Linux 2 Managed node group, Go version, etc.

**Additional context**
```
I0810 09:34:41.031980       1 nodeserver.go:352] "Using gRPC client" provider="aws" pod="nginx-deployment-86b78598c6-ssmj4"
E0810 09:36:40.925840       1 nodeserver.go:235] "failed to mount secrets store object content" err="rpc error: code = Canceled desc = context canceled" pod="default/nginx-deployment-86b78598c6-ssmj4"
I0810 09:36:40.925934       1 nodeserver.go:81] "unmounting target path as node publish volume failed" targetPath="/var/lib/kubelet/pods/959371fb-624f-4c38-8897-0ae8666f1711/volumes/kubernetes.io~csi/secrets-store-inline/mount" pod="default/nginx-deployment-86b78598c6-ssmj4"
I0810 09:36:41.480310       1 nodeserver.go:352] "Using gRPC client" provider="aws" pod="nginx-deployment-86b78598c6-ssmj4"
E0810 09:38:41.478060       1 nodeserver.go:235] "failed to mount secrets store object content" err="rpc error: code = DeadlineExceeded desc = context deadline exceeded" pod="default/nginx-deployment-86b78598c6-ssmj4"
I0810 09:38:41.478096       1 nodeserver.go:81] "unmounting target path as node publish volume failed" targetPath="/var/lib/kubelet/pods/959371fb-624f-4c38-8897-0ae8666f1711/volumes/kubernetes.io~csi/secrets-store-inline/mount" pod="default/nginx-deployment-86b78598c6-ssmj4"
I0810 09:38:42.567662       1 nodeserver.go:352] "Using gRPC client" provider="aws" pod="nginx-deployment-86b78598c6-ssmj4"
E0810 09:40:42.565651       1 nodeserver.go:235] "failed to mount secrets store object content" err="rpc error: code = Canceled desc = context canceled" pod="default/nginx-deployment-86b78598c6-ssmj4"

```

**Comment by gurudath** [comment]
Hi @StevenEmelander Can we get some details or a way to handle the issue? Its blocking us

**Comment by simonmarty** [comment]
Could you provide additional information about your environment?

- Does your private EKS cluster have outbound internet access? 
- Does the VPC the EKS cluster sits in have a service endpoint to AWS Secrets Manager? Many AWS services support private clusters, but you must use a VPC endpoint.

Here's some [documentation](https://docs.aws.amazon.com/eks/latest/userguide/private-clusters.html) on private cluster setup requirements.

**Comment by gurudath** [comment]
Hi, @simonmarty  Thaks for the details. I have created the MR so that this information is part of the README.md file also. Thanks.
https://github.com/aws/secrets-store-csi-driver-provider-aws/pull/110

**Comment by danmancuso** [comment]
@gurudath it seems this issue has been resolved.  Please reopen this case if it has not been, or open a new case if you're having any other issues.
