### ISSUE TITLE
Make the socket path configurable

### ISSUE THREAD

**Issue by aramase** [aws/secrets-store-csi-driver-provider-aws#12]
The socket endpoint is hardcoded and should be made configurable

https://github.com/aws/secrets-store-csi-driver-provider-aws/blob/01138ad64d94d1692b73fe4ddab5bd46e6712997/main.go#L28

**Comment by vito-laurenza-zocdoc** [comment]
For reference, the csi driver provides a [flag to configure the directory](https://github.com/kubernetes-sigs/secrets-store-csi-driver/blob/99cf558/cmd/secrets-store-csi-driver/main.go#L53).

**Comment by joebaro** [comment]
Thank you for opening this issue - we are looking into it.

**Comment by joebaro** [comment]
Done in in [PR 23](https://github.com/aws/secrets-store-csi-driver-provider-aws/pull/23) and [PR 24](https://github.com/aws/secrets-store-csi-driver-provider-aws/pull/24)
