### ISSUE TITLE
Add the ability to call the FIPS endpoints

### ISSUE THREAD

**Issue by tomellis** [aws/secrets-store-csi-driver-provider-aws#141]
When using the Secrets Manager provider, I want to adhere to FIPS-140-2 compliance. 
In AWS to do this I need to use the FIPS endpoints: https://aws.amazon.com/compliance/fips/ 
e.g. secretsmanager-fips.us-east-2.amazonaws.com, secretsmanager-fips.us-west-1.amazonaws.com etc

In https://github.com/aws/secrets-store-csi-driver-provider-aws/blob/main/auth/auth.go the WithSTSRegionalEndpoint call is used. 
These can be referenced in the SDK for Go by using the [UseFIPSEndpointOption](https://docs.aws.amazon.com/sdk-for-go/api/aws/endpoints/#UseFIPSEndpointOption).

Feature request: Add the capability via config to flip to the FIPS endpoint

**Comment by jbct** [comment]
Thank you for the request. We have noted this as an enhancement.

**Comment by jbct** [comment]
Fix has been merged, closing.
