### ISSUE TITLE
feature request: helm chart for installation

### ISSUE THREAD

**Issue by vito-laurenza-zocdoc** [aws/secrets-store-csi-driver-provider-aws#15]
Providing a helm chart for installation would make it easier for folks to customize the installation properties.

**Comment by joebaro** [comment]
Thank you for your feedback. We have noted this as a feature request.

**Comment by pierluigilenoci** [comment]
I support the request

**Comment by pierluigilenoci** [comment]
@joebaro is it possible to prioritize this feature given the interest of many people and the fact that it would speed up adoption by many? Thanks! ❤️

**Comment by pierluigilenoci** [comment]
@vito-laurenza-zocdoc I took the liberty of creating one: #35

**Comment by pierluigilenoci** [comment]
I did the PR but for now no sign of life from the maintainers. Will they be on vacation?

**Comment by pierluigilenoci** [comment]
@vito-laurenza-zocdoc you can find the chart here:
https://github.com/aws/eks-charts/tree/master/stable/csi-secrets-store-provider-aws

**Comment by Igor992** [comment]
@pierluigilenoci thanks for this chart, is it possible to support **annotations** here - https://github.com/aws/eks-charts/blob/master/stable/csi-secrets-store-provider-aws/templates/serviceaccount.yaml#L4

Scenario is that I need to use custom template from terraform to apply **eks.amazonaws.com/role-arn** into custom service account, but that fails because initial manifest doesn't support that option.

Docs: https://docs.aws.amazon.com/eks/latest/userguide/specify-service-account-role.html

Thanks!

**Comment by pierluigilenoci** [comment]
@Igor992 this can certainly be done. You can do a PR on the EKS Chart repo to get this feature.

If I remember correctly, however, AWS is developing a new version of the chart from scratch so I don't know how much it is worth doing. I no longer find the discussion about it.

**Comment by Igor992** [comment]
@pierluigilenoci Do we know time when this new chart will be available?

**Comment by pierluigilenoci** [comment]
You have to ask the AWS team that takes care of it.
I have no idea.

**Comment by pierluigilenoci** [comment]
@simonmarty the [chart currently published in the EKS Charts repo](https://github.com/aws/eks-charts/tree/master/stable/csi-secrets-store-provider-aws) (and also on [ArtifactHub](https://artifacthub.io/packages/helm/aws/csi-secrets-store-provider-aws)) offers many more features than the one you published [here](https://github.com/aws/secrets-store-csi-driver-provider-aws/tree/main/charts/secrets-store-csi-driver-provider-aws).

Wouldn't it be better to make the new chart feature equivalent before replacing the old one?

@Igor992 the [new one](https://github.com/aws/secrets-store-csi-driver-provider-aws/tree/main/charts/secrets-store-csi-driver-provider-aws) is out but it is very poor in features.
