### ISSUE TITLE
Required value: must specify a volume type

### ISSUE THREAD

**Issue by asdfroot** [aws/secrets-store-csi-driver-provider-aws#159]
```
$ kubectl apply -f deployment.yaml

The Deployment "nginx" is invalid:
* spec.template.spec.volumes[0]: Required value: must specify a volume type
* spec.template.spec.containers[0].volumeMounts[0].name: Not found: "secrets-store-inline"
```
What did i miss?

k8s version: `1.15` on EKS
kubernetes-sigs/secrets-store-csi-driver version: `0.0.13`

**Comment by simonmarty** [comment]
I'm unable to reproduce your issue using our [example deployment files](https://github.com/aws/secrets-store-csi-driver-provider-aws/tree/main/examples) on k8s 1.29 and the latest versions of both the CSI Driver and our provider. Without a copy of `deployment.yaml` I cannot debug this further. This is likely a syntax/configuration issue in your deployment file.
