### ISSUE TITLE
Is "Security considerations" on the main page correct?

### ISSUE THREAD

**Issue by bariscaglar** [aws/secrets-store-csi-driver-provider-aws#169]
**Describe the bug**
This is the warning on the home page:

"The AWS Secrets Manager and Config Provider provides compatibility for legacy applications that access secrets as mounted files in the pod. Security conscious applications should use the native AWS APIs to fetch secrets and optionally cache them in memory rather than storing them in the file system."

Given the ephemeral nature of the volume mounts, how is mounting a file in the pod any less secure than manually using AWS APIs to fetch secrets and cache them in memory? Both options represent an in-memory caching and if you have access to one, you have access to the other. 

**To Reproduce**

Do you also notice this bug when using a different secrets store provider (Vault/Azure/GCP...)? **Yes/No**

If yes, the issue is likely with the k8s Secrets Store CSI driver, not the AWS provider. Open an issue in [that repo](https://github.com/kubernetes-sigs/secrets-store-csi-driver/issues).

**Expected behavior**

**Environment:**
OS, Go version, etc.

**Additional context**

**Comment by simonmarty** [comment]
Secrets fetched with our caching library can be encrypted while cached by providing a custom cache hook ([here](https://github.com/aws/aws-secretsmanager-caching-java/blob/master/src/main/java/com/amazonaws/secretsmanager/caching/SecretCacheHook.java) in the Java caching library). Secrets Manager APIs are the native way to access secrets in your application.

I know you specifically asked about volume mounts, but if you wanted to store secrets from AWS Secrets Manager as Kubernetes Secrets, there are some caveats outlined in the [Kubernetes documentation on the subject](https://kubernetes.io/docs/concepts/configuration/secret/) to be mindful of.
