### ISSUE TITLE
Retrieve secrets from a list of regions

### ISSUE THREAD

**Issue by andreidum** [aws/secrets-store-csi-driver-provider-aws#18]
The provider currently supports only one  _region_ , configurable as a string.
 Given that Secrets Manager has native support for secret replication, would it be possible to improve HA by  retrieving secrets from a list of regions?

**Comment by lasred** [comment]
Thank you for your feedback. We have noted this as a feature request.

**Comment by goyalya** [comment]
Thank you for submitting the request. We currently support 2 regions to retrieve secrets and would not support list of regions at the moment.
