### ISSUE TITLE
How to specify priorityClassName for the pods ?

### ISSUE THREAD

**Issue by mk2134226** [aws/secrets-store-csi-driver-provider-aws#181]
I cant find any Helm values where we can assign priorty class name ?

**Comment by goyalya** [comment]
Thank you for your request. We are addressing it with the PR [here](https://github.com/aws/secrets-store-csi-driver-provider-aws/pull/171).

**Comment by RobCannon** [comment]
@goyalya I found this issue because I was trying to determine how to set this.  Can the documentation page (https://aws.github.io/secrets-store-csi-driver-provider-aws/) be updated to add this parameter?
