### ISSUE TITLE
Missing image pull Secrets to pull from private repo

### ISSUE THREAD

**Issue by anupash147** [aws/secrets-store-csi-driver-provider-aws#192]
this helm cannot be configured to pull images from private repository because it missing the use of imagePull secrets in its helm chart. Not sure why this was not noticed

Copy the public image to private repo as if you are a bank and then try it,

Do you also notice this bug when using a different secrets store provider (Vault/Azure/GCP...)? irrelavant

**Comment by simonmarty** [comment]
A couple quick questions:
- What container repository are you pulling the image from? (ECR, DockerHub, etc)
- Are you trying to pull the Secrets Store CSI Driver or our AWS provider?

**Comment by g-m-o-n-e-y** [comment]
@simonmarty - For instance we're mirroring external repos through a JFrog Artifactory virtual repo. We want all Helm charts to pull container images from this repo so we can ensure validity of the artifacts we use.

- Your PR #200 looks like what we need as well (see my previous attempt at #184)

**Comment by dhorner71** [comment]
@simonmarty, same as others.  we route external, public images thru our JFrog Aritifactory cloud instance and perform required security scans.  We are only able to pull from our private repo and not directly from vendor public repos.  The Secrets Store CSI driver helm chart already exposes the ability to specify a pull secret in the values.yml.  it is the AWS provider that does not allow this capability.  ty!
