### ISSUE TITLE
Regarding Plaintext secret

### ISSUE THREAD

**Issue by Akp212** [aws/secrets-store-csi-driver-provider-aws#232]
Hello Team,

I am using AWS Secret Manager to store secrets in plaintext format. Now where ever I see examples of secretproviderclass I see them as a key-value pair. So do I need to make any other changes in order to retrieve plaintext secrets from secret manager for services or it would be same. Also if you can provide an example file then that would be great.

**Comment by simonmarty** [comment]
[Here's an example](https://github.com/aws/secrets-store-csi-driver-provider-aws/blob/main/tests/BasicTestMountSPC.yaml#L41-L42)
