### ISSUE TITLE
Any tips in minimizing API calls for EKS to External Secrets Store?

### ISSUE THREAD

**Issue by pechung** [aws/secrets-store-csi-driver-provider-aws#243]
I'm using the Secrets Store CSI driver to retrieve secrets from AWS Parameter Store. According to their [docs](https://secrets-store-csi-driver.sigs.k8s.io/getting-started/usage.html), "On pod start and restart, the driver will communicate with the provider using gRPC to retrieve the secret content from the external Secrets Store you have specified in the SecretProviderClass custom resource. Then the volume is mounted in the pod as tmpfs and the secret contents are written to the volume."

Since our team deploys multiple times per day across several hundreds of nodes, this makes many thousands of API calls to AWS Parameter Store since "on pod restart, the driver communicates with the external Secrets Store". Because of this, we configs our cluster so that every 5 minutes, each node is polling Parameter Store to retrieve and update the secrets. We cannot change the polling interval due to fear of not having the most updated secrets that can cause system problems.

We're trying to optimize costs where we can. Introducing a layer in between the Secrets Store CSI Driver and the Secrets Store CSI Provider as some sort of cache would minimize the API calls but likely not possible to change how Secrets Store CSI works itself. We can't change the polling interval, and can't change some sort of event-triggered workflow since, again, they can't change the way Secrets Store CSI works. Any thoughts?

**Comment by jbct** [comment]
While the approach you're suggesting sounds like a good solution, there aren't any best practices or tips we can provide for your specific implementation. I would encourage you to take a look at the [Well Architected](https://aws.amazon.com/architecture/well-architected/) framework for additional considerations.
