### ISSUE TITLE
Feature: optionally return secret contents to driver instead of writing files

### ISSUE THREAD

**Issue by tam7t** [aws/secrets-store-csi-driver-provider-aws#27]
The driver's gRPC interface has been expanded to allow providers to [return a view of the filesystem in the RPC response](https://github.com/kubernetes-sigs/secrets-store-csi-driver/blob/e2f85d3a3a8d3c87fd24170e213284aa70f61e07/provider/v1alpha1/service.proto#L64-L69), making the driver responsible for writing the files to the actual mount.

Creating this bug as the AWS-specific version of https://github.com/kubernetes-sigs/secrets-store-csi-driver/issues/551

**Comment by lasred** [comment]
Thank you for your feedback. We have noted this as a feature request.

**Comment by joebaro** [comment]
Sorry for the delay. This has been pushed in [PR 33](https://github.com/aws/secrets-store-csi-driver-provider-aws/pull/33).
