### ISSUE TITLE
README has conflicting information about EKS/ECS

### ISSUE THREAD

**Issue by onwsk8r** [aws/secrets-store-csi-driver-provider-aws#271]
**Describe the bug**

It's a doc bug, could have happened to anyone: https://github.com/aws/secrets-store-csi-driver-provider-aws/blob/8d3e5030370790421828ad968f08b2d2c39b9331/README.md?plain=1#L11

**To Reproduce**

1. View the repository README

Do you also notice this bug when using a different secrets store provider (Vault/Azure/GCP...)? **Yes/No** No

**Expected behavior**: The README should contain accurate information

**Additional context**: Hey, if this is under the AWS Github org (is that a conflict of interest?) I'm assuming you know that there's no such thing as "EKS using ECS". I'm happy to PR in the change if someone wants to clear it up.

Does this work with ECS? ECS Fargate? Sounds like a "no" on EKS Fargate.. What about EKS with a combination of Fargate and EC2 nodes? What if I have EC2 nodes that are not part of a node group? What about EKS Anywhere? What about EC2 nodes using a home-baked AMI? What about self-hosted k8s on AWS? I realize that's a lot of questions- these are all questions I would expect to get asked at work when suggesting something like this.

**Comment by jbct** [comment]
Thanks for the report, onwsk8r. One of our engineers is taking a look.
