### ISSUE TITLE
Permission denied when policy restricts to current version of secret

### ISSUE THREAD

**Issue by serain** [aws/secrets-store-csi-driver-provider-aws#28]
In the spirit of "least privileges", it's arguably a good practice restrict access to only the current version of a secret. Unfortunately the `secrets-store-csi-driver-provider-aws` runs into permission issues when doing so.

Steps to reproduce:
* Create a role with a policy attached that only allows reading the current version of a secret:
```
{
    "Version": "2012-10-17",
    "Statement": {
        "Effect": "Allow",
        "Action": ["secretsmanager:GetSecretValue", "secretsmanager:DescribeSecret"],
        "Resource": "arn:aws:secretsmanager:eu-west-1:388662706032:secret:k8s-secret_foo_bar",
        "Condition": {
            "ForAnyValue:StringEquals": {
                "secretsmanager:VersionStage": "AWSCURRENT"
            }
        }
    }
}
```
* See pod is stuck in `ContainerCreating` and events show `PermissionDenied` on reading the secret.
* Remove the `Condition` from the policy, recreate the pod, watch it successfully read the secret.

**Comment by joebaro** [comment]
The practice of restricting GetSecretValue to only the current version is not considered a best practice. The secret provides access and the privileges are provided by whatever the secret is connected to, such as a database. Either the old passwords are no longer valid or they provide access to the same set privileges (unless someone is repurposing secrets; which is not a good idea). There are also good reasons to let users access previous passwords (e.g. when a database is restored from an old backup).

The use of "secretsmanager:VersionStage" was shown in some of the API documents as an example of how to place restrictions on parameters and was not intended to become a common practice. We are working on replacing these examples in the docs.
