### ISSUE TITLE
Add high priority to DaemonSet

### ISSUE THREAD

**Issue by fpinyolmargalef** [aws/secrets-store-csi-driver-provider-aws#298]
We are running an EKS cluster with Horizontal Pod Autoscaler and Karpenter for node autoscaling.

When several pods with our application are needed and no space is available in existing nodes, Karpenter, as expected, creates a
new node and tries to start all our pods in it, in addition to csi-secrets-store-provider-aws pod.
But in some occasion, our pods were created first, occupying all the node resources, and csi-secrets-store-provider-aws could not be created. This prevented our pods to work correctly, as they depend on secrets provided by csi-secrets-store-provider-aws.

As explained in https://kubernetes.io/docs/concepts/scheduling-eviction/pod-priority-preemption/, would it be a good idea to add "priorityClassName: system-node-critical" to DaemonSet in aws-provider-installer.yaml?

We have done it with:
```
# verify that yq is installed
command -v yq >/dev/null 2>&1 || (echo "yq command not found. Please install it from https://mikefarah.gitbook.io/yq/"; exit 1)
curl -o aws-provider-installer.yaml https://raw.githubusercontent.com/aws/secrets-store-csi-driver-provider-aws/main/deployment/aws-provider-installer.yaml

# add priorityClassName: system-node-critical
# https://kubernetes.io/docs/concepts/scheduling-eviction/pod-priority-preemption/
# https://kubernetes.io/docs/tasks/administer-cluster/guaranteed-scheduling-critical-addon-pods/
yq -i 'select(.kind=="DaemonSet") | .spec.template.spec.priorityClassName = "system-node-critical"' aws-provider-installer.yaml
	
kubectl apply -f aws-provider-installer.yaml	
```

**Comment by simonmarty** [comment]
This is already a configuration option we expose in our [Helm chart](https://github.com/aws/secrets-store-csi-driver-provider-aws/blob/main/charts/secrets-store-csi-driver-provider-aws/values.yaml#L23).

**Comment by goyalya** [comment]
Closing the issue. Please feel free to open a new issue if additional support is required.
