### ISSUE TITLE
provider-volume: default socket location under /etc is suboptimal

### ISSUE THREAD

**Issue by lucab** [aws/secrets-store-csi-driver-provider-aws#31]
This driver uses a local Unix socket (`aws.sock`) which by default is located under `/etc/kubernetes/secrets-store-csi-providers`: https://github.com/aws/secrets-store-csi-driver-provider-aws/blob/19425533920612e6743cf58a6f836d97de6f0592/main.go#L23

This default location is somehow strange and suboptimal, as the filesystem entry is neither a regular file (which could be backup'd via usual backup tools) nor it contains persistent configuration (which is meant to persist across reboots).

This is particularly impactful on ostree-based systems, where the content of /etc is versioned and can be atomically rolled back (see [docs](https://ostreedev.github.io/ostree/atomic-upgrades/#assembling-a-new-deployment-directory)).

As the socket is a local ephemeral entry in the filesystem, it could be moved to a better non-persistent hierarchy like `/run`.

**Comment by cgwalters** [comment]
A good rule for "should this file be in `/etc`" is "would an administrator reasonably use `vi` on it?".

**Comment by joebaro** [comment]
This is the historical default used by the [secrets-store-csi-driver](https://github.com/kubernetes-sigs/secrets-store-csi-driver); for which this is a plugin. The path is configurable, but the default can not be changed without breaking compatibility.

**Comment by cgwalters** [comment]
One option is to delete the file when the process shuts down, are you OK with that?
