### ISSUE TITLE
[Question] Inside .yaml, there is a way to retrieve all aws secrets without pass keys?

### ISSUE THREAD

**Issue by ValchanOficial** [aws/secrets-store-csi-driver-provider-aws#311]
- Inside ci.yaml
- I pass the secret name
- Then I get all keys/values without passing keys names inside .yaml

Is this possible?
```
      env:
            - name: mysecretatsecretmanager 
           # get all key: value and create envs
```

Like this:
https://kubernetes.io/pt-br/docs/concepts/configuration/secret/
```
      envFrom:
      - secretRef:
          name: mysecretatsecretmanager
          
```

**Comment by simonmarty** [comment]
This is blocked by https://github.com/kubernetes-sigs/secrets-store-csi-driver/issues/529
