### ISSUE TITLE
Request support for adding custom CA certs to helm chart

### ISSUE THREAD

**Issue by jameshcovington** [aws/secrets-store-csi-driver-provider-aws#372]
When I try to run a pod in region us-isob-east-1 I get the error "tls: filed to verify certificates: x509: certificate signed by unknown authority" when trying to connect to an AWS Endpoint. Believe this is due to a different CA root bundle in this region.
Request support be added for additional ca certs, e.g. values.yaml entries to support an optional volume mount.

**Comment by jameshcovington** [comment]
also, I believe there would be some additional refactoring required for what is customarily a fixed DNS suffix, namely "amazonaws.com" which is not valid in the us-isob-east-1 region.

**Comment by simonmarty** [comment]
Captured in #281
