### ISSUE TITLE
Consider adding a changelog or useful notes to Github releases

### ISSUE THREAD

**Issue by gunzy83** [aws/secrets-store-csi-driver-provider-aws#386]
Hello,

This is not really a feature request for this program but the repo itself. When operating a cluster we have to check changelogs of all of the applications we are running to ensure there are no breaking changes or changes that would affect how we operate the application.

We are now also using [Renovate](https://github.com/renovatebot/renovate) to automate helm upgrades (via PRs) to our Pulumi managed EKS clusters and this repo does not include either a CHANGELOG.md file anywhere and the Github releases do not include any useful information about what was actually released. Adding either of these will ease the burden of checking all commits between versions.

I realise that this will be a change to the release workflow (which looks to be manual right now) but there are tools like [Release Please](https://github.com/googleapis/release-please) that make this easy if you are using conventional commits.

Thanks.

**Comment by simonmarty** [comment]
I generated release notes to our various GitHub releases. We use chart-releaser to release new versions of our helm chart which creates the release in GitHub. I don't know that that tool supports making changelogs.

You can always look at the git history. We tag each commit with the version number.

**Comment by gunzy83** [comment]
I see the releases now have descriptive notes on them, which works just fine. While our primary repo is up-to-date, I tested this on a test repo and renovate generates a nice log from the release objects:

Before:
![image](https://github.com/user-attachments/assets/1f1fcbb5-ad6a-4852-ba77-8b80fd64d963)

After:
![image](https://github.com/user-attachments/assets/82ce417f-e6e0-4d64-aa4a-9703ca4f018e)

Thanks again.
