### ISSUE TITLE
not creating k8s secrets

### ISSUE THREAD

**Issue by srreddy2020** [aws/secrets-store-csi-driver-provider-aws#392]
I have deployed below Helm Charts as daemonSets in K8s Cluster.
1)secrets-store-csi-driver-1.4.4
2)secrets-store-csi-driver-provider-aws-0.3.9

Instead of Mounting the secrets into Pod, i would like to have k8s native secrets to get secrets from Aws Secrets Manager
When we deploy StorageProviderClass its not creating Secrets.
Pod stuck with Error: secret "mysecret-k8s" not found

IAM Role working fine and storageproviderClass Yaml also looks fine, as its working fine when i add Volume\volumeMounts to the POD,i am getting secrets from AWS.

Which provider are you using:
AWS Secrets Manager

Environment:

Secrets Store CSI Driver version: v1.4.4
Kubernetes version: v1.27
YAML file below..
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
namespace: csi-provider
name: mysecret
spec:
provider: aws
secretObjects:
- secretName: mysecret-k8s
type: Opaque
data:
- objectName: "dataminds_svcs_database_dbpassword"
key: "dataminds_svcs_database_dbpassword"
- objectName: "dataminds_svcs_idm_password"
key: "dataminds_svcs_idm_password"
parameters:
objects: |
- objectName: "ci/apiplt/test"
objectType: "secretsmanager"

apiVersion: apps/v1
kind: Deployment
metadata:
name: nginx1
namespace: csi-provider
spec:
replicas: 1
selector:
matchLabels:
run: nginx1
template:
metadata:
annotations:
secrets-store.csi.k8s.io/used: "true"
labels:
run: nginx1
spec:
containers:
- image: nginx:stable-alpine
name: nginx1
env:
- name: dataminds_svcs_database_dbpassword
valueFrom:
secretKeyRef:
name: mysecret-k8s
key: dataminds_svcs_database_dbpassword
- name: dataminds_svcs_idm_password
valueFrom:
secretKeyRef:
name: mysecret-k8s
key: dataminds_svcs_idm_password
serviceAccountName: csi-provider

Please look into it and let me know if i miss anyting

**Comment by gdasson** [comment]
You are looking at the wrong project for native K8s secrets. If you are interested in native k8s secrets only, you'd use a project like ESO: https://external-secrets.io/latest/

**Comment by simonmarty** [comment]
I think https://secrets-store-csi-driver.sigs.k8s.io/topics/sync-as-kubernetes-secret is what you want.

If you have more questions about this, open an issue at https://github.com/kubernetes-sigs/secrets-store-csi-driver

This doesn't look like it is specific to our AWS provider.

**Comment by ericvolp12** [comment]
That doc page describes features that this provider doesn't seem to support. When configured according to the docs, no kubernetes secret objects are created in the cluster. It seems like this driver implementation might be missing some part of the Secret Store CSI driver spec.
