### ISSUE TITLE
Question: Is hostNetwork required?

### ISSUE THREAD

**Issue by groodt** [aws/secrets-store-csi-driver-provider-aws#40]
The csi-secrets-store-provider-aws DaemonSet YAML file is setup with `hostNetwork` access. This is obviously not ideal from a security perspective (and from a port clash perspective).

Does this workload actually need `hostNetwork`?

**Comment by groodt** [comment]
cc @joebaro @lasred

**Comment by groodt** [comment]
Any thoughts @joebaro @lasred?

Is there a more appropriate place for me to ask questions like this? I didn't notice anything in the CONTRIBUTING guidelines, but perhaps I've missed something.

**Comment by groodt** [comment]
Ping @joebaro @lasred

**Comment by HenriWilliams** [comment]
+1

**Comment by simonmarty** [comment]
We're actively looking into this
