### ISSUE TITLE
localstack support

### ISSUE THREAD

**Issue by yatanasov-hs** [aws/secrets-store-csi-driver-provider-aws#48]
Aws csi driver does not support localstack (https://github.com/localstack/localstack) for local development. Is this something in your roadmap ?

**Comment by joebaro** [comment]
This AWS provider is a plugin to the [Secret Store CSI driver](https://github.com/kubernetes-sigs/secrets-store-csi-driver) and as such must run in an EKS cluster with the driver. It would not be possible to run this outside of that framework.

**Comment by SizZiKe** [comment]
@joebaro @yatanasov-hs  this isn't true, I'm about to PR it :)
