### ISSUE TITLE
Question: I want each to have an environment variable value.

### ISSUE THREAD

**Issue by khs3131** [aws/secrets-store-csi-driver-provider-aws#49]
I have one aws secret manager. There are five secret values in aws secret manager: username, password, engine, host, and port. I want to display the values of username, password, engine, host, and port respectively when connecting to the inside of the pod (exec -it) using the env field. For example, use the 'kubectl exec -it -- /bin/bash' command to access the pod and the result of the environment variable is USERNAME = admin / PASSWORD = ;g{}. /engine=mysql/host=rds01.mysql/port=3306 I want to show. But now it is displayed as a single line in json format as below. USERNAME=(PASSWORD={"username": "admin", "password": ";g{}.", "engine": "mysqldb", "host" : "rds01.mysql", "port": 3306} Is there any way to solve this?

**Comment by joebaro** [comment]
Please see the jmesPath description in the [Secrets Manager docs](https://docs.aws.amazon.com/secretsmanager/latest/userguide/integrating_csi_driver.html#integrating_csi_driver_SecretProviderClass) and in the [README](https://github.com/aws/secrets-store-csi-driver-provider-aws#secretproviderclass-options).
