### ISSUE TITLE
Unknown desc = Name already in use for objectName

### ISSUE THREAD

**Issue by ggeorgievhs** [aws/secrets-store-csi-driver-provider-aws#50]
Hello,
When using the ASCP (Aws Secret Configuration Provider) to retrieve some secrets from aws secret manager, I receive the error from the title of the issue when you try to have more than one secret objects in Kubernetes, fetched from the same secret path/name in aws secret manager. Here is an example:
secret1 = secret_name_in_aws_secret_manager
secret2 = secret_name_in_aws_secret_manager
Then use these secret1 and secret2 in the same or even different SecretProviderClass produce an error.

I would like to ask you if this is expected behaviour and if this could be fixed or there is a proper workaround. To avoid this, after trying different SecretProviderClass and different mounts, I've just created two more secrets with different name but I am looking for a better solution. I didn't find anything related in the issues here, in the issues page of the csi-driver and the documentation.
Thank you in advance!

**Comment by joebaro** [comment]
This is expected behavior.

In the [Secrets Manager docs](https://docs.aws.amazon.com/secretsmanager/latest/userguide/integrating_csi_driver.html#integrating_csi_driver_SecretProviderClass) it calls out that objectName becomes the file name of the secret in the pod (which is why it is required to be unique).

The work around is to use objectAlias to give the secret a different file name.

**Comment by ggeorgievhs** [comment]
The problem is not that we have two equal secret names but the problem is that i want to have two objectAlias from the same aws secret. The error is not about duplicated name of the kubernetes object but about the source of these objects (cause it's the same). Do you think you can have two objectAlias from the same source?

**Comment by donalddewulf** [comment]
Would love to see this feature added. Maybe allow us to provide a list in objectAlias?

**Comment by giedriuskilcauskas** [comment]
Setting `objectAlias` doesn't workaround the issue. It still tries to mount secret as `objectName` if both objects coming from the same SM secret
