### ISSUE TITLE
SecretsManager plaintext support

### ISSUE THREAD

**Issue by freakk82** [aws/secrets-store-csi-driver-provider-aws#51]
I am required to mount some secrets in environment variables, but the ARNs are of plaintext secrets in AWS SecretsManager.
The documentation examples mention only key/value secrets, so I guess plaintext secrets are not supported.
Can anyone confirm that is the case, and whether there is any plan to support plaintext secrets in addition to JSON key/value secrets?
They are a valid option in AWS, therefore it's not unlikely for a developer to be required to fetch them.

**Comment by jhughes-mc** [comment]
We're using plaintext secrets, it's supported. Although maybe not officially...

**Comment by rjcoupe** [comment]
Would someone be able to provide an example of how this is done? As @freakk82 suggests, all of the documentation (that I've seen) is aimed squarely at K/V pairs.

**Comment by ariksidney** [comment]
We just came across this yesterday and also found a working solution for it. I'll create a PR and update the README with some instructions.
