### ISSUE TITLE
Is storage memory based or disk based ?

### ISSUE THREAD

**Issue by sukrit007wawa** [aws/secrets-store-csi-driver-provider-aws#53]
I was going through the source code, but needed to confirm if the storage for mounting secrets is memory-based or disk-based?

**Comment by joebaro** [comment]
This is under the control of the Secret Store CSI driver (for which this code is a provider plugin). The [Secret Store driver docs](https://github.com/kubernetes-sigs/secrets-store-csi-driver/blob/main/docs/book/src/getting-started/usage.md) state that the secrets are mounted in a tmpfs (memory based) file system.
