### ISSUE TITLE
Provide a v1.0.0 release

### ISSUE THREAD

**Issue by nlamirault** [aws/secrets-store-csi-driver-provider-aws#55]
What do you think about make a v1.0.0 release like others providers : 
- https://github.com/Azure/secrets-store-csi-driver-provider-azure/issues/676
- https://github.com/GoogleCloudPlatform/secrets-store-csi-driver-provider-gcp/issues/148

**Comment by kitos9112** [comment]
I'm upvoting this GH issue of course. Is there any update on this area?

**Comment by simonmarty** [comment]
Closing. We follow [SemVer2](https://semver.org/). We will stick to the current major version number until we introduce breaking changes that require a major version bump.
