### ISSUE TITLE
Permission Error

### ISSUE THREAD

**Issue by vitarkah** [aws/secrets-store-csi-driver-provider-aws#58]
`kubectl logs --follow -n kube-system csi-secrets-store-secrets-store-csi-driver-knkbc -c secrets-store`

The k8s secret sync does not seem to be working....

Ran into this error `E1103 15:04:34.473126       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.21.1/tools/cache/reflector.go:167: Failed to watch *v1.Secret: failed to list *v1.Secret: secrets is forbidden: User "system:serviceaccount:kube-system:secrets-store-csi-driver" cannot list resource "secrets" in API group "" at the cluster scope` and unable to figure what exactly needs to be done.

**Comment by vitarkah** [comment]
Figured out...
helm upgrade --install -n kube-system --set syncSecret.enabled=true csi-secrets-store secrets-store-csi-driver/secrets-store-csi-driver

Default
https://github.com/kubernetes-sigs/secrets-store-csi-driver/blob/221ef44211750661b2407e608ff707517d7a940a/charts/secrets-store-csi-driver/values.yaml#L186-L188

**Comment by vitarkah** [comment]
Figured out...
helm upgrade --install -n kube-system --set syncSecret.enabled=true csi-secrets-store secrets-store-csi-driver/secrets-store-csi-driver

Default
https://github.com/kubernetes-sigs/secrets-store-csi-driver/blob/221ef44211750661b2407e608ff707517d7a940a/charts/secrets-store-csi-driver/values.yaml#L186-L188

**Comment by mafeifan** [comment]
hmm. I have turned on syncSecret.enabled, but still have same error

```
 I0129 02:22:14.771879       1 exporter.go:35] "initializing metrics backend" backend="prometheus"

 I0129 02:22:14.793056       1 main.go:182] starting manager

 I0129 02:22:14.894887       1 secrets-store.go:46] "Initializing Secrets Store CSI Driver" driver="secrets-store.csi.k8s.io" version="v1.3.0" buildTime="2022-12-13-20:41"

 I0129 02:22:14.930138       1 server.go:121] "Listening for connections" address="//csi/csi.sock"

 I0129 02:22:15.893990       1 request.go:601] Waited for 1.04026038s due to client-side throttling, not priority and fairness, request: GET:https://10.100.0.1:443/apis/monitoring.coreos.com/v1alpha1?timeout=32s

 I0129 02:22:16.085495       1 nodeserver.go:365] node: getting default node info

 I0129 02:23:22.811678       1 nodeserver.go:359] "Using gRPC client" provider="aws" pod="nginx-deployment-k8s-secrets-66d5f46844-l99jb"

 E0129 02:23:23.302524       1 nodeserver.go:242] "failed to mount secrets store object content" err="rpc error: code = Unknown desc = Failed to fetch secret from all regions: /kone/govplt/elasticache/secret" pod="default/nginx-deployment-k8s-secrets-66d5f46844-l99jb"

 I0129 02:23:23.302641       1 nodeserver.go:88] "unmounting target path as node publish volume failed" targetPath="/var/lib/kubelet/pods/0bc06bcd-716a-4511-8e72-cc43334a4d8a/volumes/kubernetes.io~csi/secrets-store-inline/mount" pod="default/nginx-deployment-k8s-secrets-66d5f46844-l99jb"

 I0129 02:23:23.915727       1 nodeserver.go:359] "Using gRPC client" provider="aws" pod="nginx-deployment-k8s-secrets-66d5f46844-l99jb"
```
