### ISSUE TITLE
How would I limit who can mount what Secrets into what namespaces?

### ISSUE THREAD

**Issue by tomsucho** [aws/secrets-store-csi-driver-provider-aws#59]
Hey Guys,
how would I prevent folks from one namepspace to also mount secrets from Secret Manager that are mounted already in some other namespace?
What would be access control pattern to use here to make sure specific namespace gets only access to a specific  SecretManager secrets? Normally that would be handled via separate IAM roles, but in this case the cluster wide csi driver uses one and the same role for all namespaces? 
Aplologies If I misunderstood something, I'm new to this and testing this out now.
Cheers, Tomasz

**Comment by peteroruba** [comment]
You configure your Pods with a particular ServiceAccount, which in turn via "IAM roles for Service Accounts"(https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts.html) inherits the corresponding IAM permissions what secret can be accessed. The permission to access a particular secret is therefore tied to the ServiceAccount attached to a pod, not to the CSI driver.

**Comment by tomsucho** [comment]
okay thanks, that was not clear really from the docs, I went with ESO in the end.
