### ISSUE TITLE
Bottlerocket support

### ISSUE THREAD

**Issue by mikestef9** [aws/secrets-store-csi-driver-provider-aws#6]
When launching the AWS provider on a [Bottlerocket](https://github.com/bottlerocket-os/bottlerocket) node, you get the following error

```
38f9d34f5435:~ mikestef$ k logs csi-secrets-store-provider-aws-46rkg -n kube-system
I0423 00:23:23.096328       1 main.go:25] Starting secrets-store-csi-driver-provider-aws version 1.0.r1-2021.04.22.19.04
F0423 00:23:23.096808       1 main.go:44] Failed to listen on unix socket. error: listen unix /etc/kubernetes/secrets-store-csi-providers/aws.sock: bind: permission denied
goroutine 1 [running]:
k8s.io/klog/v2.stacks(0xc00000e001, 0xc0004a6000, 0xac, 0xce)
	/home/ec2-user/go/pkg/mod/k8s.io/klog/v2@v2.3.0/klog.go:996 +0xb9
k8s.io/klog/v2.(*loggingT).output(0x25bb0e0, 0xc000000003, 0x0, 0x0, 0xc00049c2a0, 0x251de21, 0x7, 0x2c, 0x0)
	/home/ec2-user/go/pkg/mod/k8s.io/klog/v2@v2.3.0/klog.go:945 +0x191
k8s.io/klog/v2.(*loggingT).printf(0x25bb0e0, 0x3, 0x0, 0x0, 0x195df6b, 0x2a, 0xc0003bbf18, 0x1, 0x1)
	/home/ec2-user/go/pkg/mod/k8s.io/klog/v2@v2.3.0/klog.go:733 +0x17a
k8s.io/klog/v2.Fatalf(...)
	/home/ec2-user/go/pkg/mod/k8s.io/klog/v2@v2.3.0/klog.go:1463
main.main()
	/home/ec2-user/secrets-store-csi-driver-provider-aws/main.go:44 +0x2df
```

**Comment by bcressey** [comment]
Bottlerocket's `/etc` is not writable by most processes, so this host path volume will be created but won't be writable:
```
      volumes:
        - name: providervol
          hostPath:
            path: "/etc/kubernetes/secrets-store-csi-providers"
```

Ideally you'd use a path somewhere under `/var` for any state that needs to be saved, and under `/run` for anything ephemeral. `/etc` is a strange place to create sockets even on systems where it's allowed.

**Comment by StevenEmelander** [comment]
Thank you for reporting this issue. It appears that /etc/kubernetes/secrets-store-csi-providers is the standard location for secret store csi providers, and we strive to be as consistent as we can. We are investigating if there are any other ways to enable support in Bottlerocket that does not involve changing this standard location. Please let us know if you have ideas.

**Comment by joebaro** [comment]
Closing in favor of https://github.com/bottlerocket-os/bottlerocket/issues/1524
