### ISSUE TITLE
Not able to refer aws parameter store values in my pods.

### ISSUE THREAD

**Issue by pareshtw** [aws/secrets-store-csi-driver-provider-aws#60]
By using SecretProviderClass object we can specify the key for secret objects & we can use them in pod by referring the same key. But if I want to use parameter store values how can I refer them in my pods ? As I can't define any key for parameter store values & also it does not support character '/'(parameter store key start with '/')

I need a solution of how can I refer my parameter store values in my pods. 

error:- Getting below error while installing the helm charts.
Error: INSTALLATION FAILED: DaemonSet.apps "fluentbit-daemonset" is invalid: [spec.template.spec.containers[0].env[1].valueFrom.secretKeyRef.key: Invalid value: "/dev/eks/endpoint": a valid config key must consist of alphanumeric characters, '-', '_' or '.' (e.g. 'key.name',  or 'KEY_NAME',  or 'key-name', regex used for validation is '[-._a-zA-Z0-9]+'), spec.template.spec.containers[0].env[2].valueFrom.secretKeyRef.key: Invalid value: "/dev/eks/ca": a valid config key must consist of alphanumeric characters, '-', '_' or '.'

**Comment by simonmarty** [comment]
For example, [here](https://github.com/aws/secrets-store-csi-driver-provider-aws/blob/main/tests/BasicTestMountSPC.yaml) we mount some parameter store values, you can make them show up as [file mounts in your pod](https://github.com/aws/secrets-store-csi-driver-provider-aws/blob/main/tests/BasicTestMount.yaml)

**Comment by jbct** [comment]
Closing based on the examples provided above.
