### ISSUE TITLE
Is this repository still actively developed?

### ISSUE THREAD

**Issue by bgdnlp** [aws/secrets-store-csi-driver-provider-aws#65]
Hi,

This repository is not longer under development, is it? Development moved to https://github.com/kubernetes-sigs/secrets-store-csi-driver ?

**Comment by schwichti** [comment]
As far as I understand you still need both, the provider-agnostic secrets-store-csi-driver and the aws provider (this repo). However, you raised my attention to the question whether this project is actively maintained...

**Comment by bgdnlp** [comment]
You're right, I should have RTFM'd first:
> You first install the Kubernetes Secrets Store CSI Driver, and then you install the ASCP.

That said, I'm updating the title. The last commit was 6 months ago and there are a bunch of issues and pull requests that could use some attention. Of interest to me are #46 (ability to pull the entire secret into K8s without having to specify each key individually) and #22 (it doesn't work on Graviton?).

I'm setting up a new set of clusters and I'm wondering if I should use this implementation or go with https://github.com/external-secrets/kubernetes-external-secrets.

**Comment by kitos9112** [comment]
Yes, I'd expect AWS to release more often versions of this secret CSI provider and make it work with the new v1 version https://github.com/kubernetes-sigs/secrets-store-csi-driver/releases/tag/v1.0.0

**Comment by pierluigilenoci** [comment]
@bgdnlp dispassionate opinion: I would use official AWS software to do this. 

@kitos9112 the official chart support the Secret Store CSI Driver v1.* https://github.com/aws/eks-charts/tree/master/stable/csi-secrets-store-provider-aws

**Comment by bgdnlp** [comment]
> @bgdnlp dispassionate opinion: I would use official AWS software to do this.

I agree, I would also use official AWS software in this case, which is why I'm here. Unfortunately it seems to be missing a couple of features that I had hoped would be present by now. Hence my asking about the status of this driver, because I know they are customer driven. It's not a demand, I'm not complaining about anything.

**Comment by pierluigilenoci** [comment]
@bgdnlp unfortunately AWS developers are not very responsive here on GitHub.
To get the PR of the chart of the `csi-secrets-store-provider-aws` I had to struggle for weeks and I had to bother half of AWS Dev department. 😝

**Comment by simonmarty** [comment]
@bgdnlp We made a note of the increased interest on the two feature requests you mentioned.
