### ISSUE TITLE
Error connecting to provider "aws"

### ISSUE THREAD

**Issue by TheChickenDevOps** [aws/secrets-store-csi-driver-provider-aws#68]
Hello, I'm using latest helm chart here https://raw.githubusercontent.com/kubernetes-sigs/secrets-store-csi-driver/master/charts and met the errors:

`GRPC error: failed to mount secrets store objects for pod default/nginx-deployment-75bfbbcf99-bwpqd, err: error connecting to provider "aws": provider not found: provider "aws"`

when create a new SecretProviderClass.
I followed all the instruction but unfortunately it doesn't seem to work, have any of you had the same problem?

**Comment by pierluigilenoci** [comment]
Try using this:
https://artifacthub.io/packages/helm/aws/csi-secrets-store-provider-aws

**Comment by TheChickenDevOps** [comment]
It Works! Thanks!

**Comment by afranzi** [comment]
Any reason of why the chart in the documentation doesn't work but the one in artifachub does?

**Comment by afranzi** [comment]
Adding the link the other repo for visibility -- https://github.com/aws/eks-charts/tree/master/stable/csi-secrets-store-provider-aws :)

**Comment by pierluigilenoci** [comment]
@afranzi I don't understand exactly what you mean. 
The [chart on GitHub](https://github.com/aws/eks-charts/tree/master/stable/csi-secrets-store-provider-aws) is exactly the same published on [ArtifactHub](https://artifacthub.io/packages/helm/aws/csi-secrets-store-provider-aws).

**Comment by afranzi** [comment]
Sure, I was trying to understand why the chart published was different from the documentation of this repo until I read the thread where you were trying to approach AWS developers and moved the code into the other repo -- https://github.com/aws/eks-charts/ .

**Comment by pierluigilenoci** [comment]
@afranzi maybe I understood.

The documentation in this repo talks about the [secrets-store-csi-driver](https://github.com/kubernetes-sigs/secrets-store-csi-driver) chart for the CSI **driver**.
This repo however contains the source of the **provider**.
The chart on the eks-chart repo is the one to install the **provider**  (which uses that of the secrets-store-csi-driver chart as a dependency).

They are two different charts for two different software that both serve to integrate AWS Secret Managers with EKS. 
The driver is maintained by SIG Kubernetes, the provider from AWS.
For example, [here](https://github.com/kubernetes-sigs/secrets-store-csi-driver/blob/main/docs/book/src/concepts.md#provider-for-the-secrets-store-csi-driver) you can find the list of all possible providers to integrate the driver in all cloud providers. 

Ref: 
* https://secrets-store-csi-driver.sigs.k8s.io/introduction.html
* https://secrets-store-csi-driver.sigs.k8s.io/providers.html
* https://github.com/kubernetes-sigs/secrets-store-csi-driver/blob/main/docs/book/src/concepts.md#provider-for-the-secrets-store-csi-driver
