### ISSUE TITLE
Pin Docker image to specific version

### ISSUE THREAD

**Issue by gabegorelick** [aws/secrets-store-csi-driver-provider-aws#7]
The `csi-secrets-store-provider-aws` DaemonSet uses the `latest` tag. It should probably be pinned to a specific release to avoid breaking when newer images are published. 

https://github.com/aws/secrets-store-csi-driver-provider-aws/blob/01138ad64d94d1692b73fe4ddab5bd46e6712997/deployment/aws-provider-installer.yaml#L61

As a workaround, you can use [private builds](https://github.com/aws/secrets-store-csi-driver-provider-aws#private-builds) to avoid the issue.

**Comment by juv** [comment]
This also violates a policy in the EKS security best practices, i.e. https://github.com/aws/aws-eks-best-practices/blob/master/policies/opa/gatekeeper/constraint-templates/6-dep-latest-version-template.yaml 

Users following those best practices in their cluster can not use the installation manifests without changing it manually

**Comment by vito-laurenza-zocdoc** [comment]
This should ideally be handled in a helm chart as requested in #15

**Comment by joebaro** [comment]
Thank you for opening this issue - we are looking into it.

**Comment by lasred** [comment]
https://github.com/aws/secrets-store-csi-driver-provider-aws/pull/21 addresses this issue
