### ISSUE TITLE
`helm repo` command in README.md shows 404 error

### ISSUE THREAD

**Issue by MasatoshiTada8888** [aws/secrets-store-csi-driver-provider-aws#72]
I tried to install Secrets Store CSI Driver using `helm repo` command written in README.md, but I got 404 error (see below).

```
$ helm repo add secrets-store-csi-driver https://raw.githubusercontent.com/kubernetes-sigs/secrets-store-csi-driver/master/charts
Error: looks like "https://raw.githubusercontent.com/kubernetes-sigs/secrets-store-csi-driver/master/charts" is not a valid chart repository or cannot be reached: failed to fetch https://raw.githubusercontent.com/kubernetes-sigs/secrets-store-csi-driver/master/charts/index.yaml : 404 Not Found
```

According to [the official site of Secrets Store CSI Driver](https://secrets-store-csi-driver.sigs.k8s.io/getting-started/installation.html), the correct command is below:

```
$ helm repo add secrets-store-csi-driver https://kubernetes-sigs.github.io/secrets-store-csi-driver/charts
```

**Comment by pierluigilenoci** [comment]
@MasatoshiTada8888 maybe you can try to use the chart https://github.com/aws/eks-charts/tree/master/stable/csi-secrets-store-provider-aws

**Comment by simonmarty** [comment]
Thanks for the notice, we updated our README to reflect the new URL
