### ISSUE TITLE
Informational messages are logged as errors

### ISSUE THREAD

**Issue by fubar** [aws/secrets-store-csi-driver-provider-aws#74]
Our logs show the below messages logged frequently and at error level:

```
I0322 06:00:50.813426       1 server.go:107] Servicing mount request for pod [...] in namespace default using service account [...] with region eu-west-1
I0322 06:00:51.010475       1 auth.go:123] Role ARN for [...] is arn:aws:iam::[...]
```

These are informational messages that should not be treated like errors.

**Comment by pierluigilenoci** [comment]
@fubar these are informational messages.
Why do you say they are treated like errors?

Keep in mind that Klog (the library used for logging) is affected by a fairly serious bug regarding error levels.
And I don't see any fixes on the horizon anytime soon.

Ref: https://github.com/kubernetes/klog/issues/212

**Comment by fubar** [comment]
Interesting, that may as well be the cause. We're using a standard Datadog agent setup for logging, and all of those log events are logged at the error level in Datadog.

Does the AWS provider have any configuration options for logging?

**Comment by pierluigilenoci** [comment]
@fubar The CSI driver [yes](https://github.com/kubernetes-sigs/secrets-store-csi-driver/blob/main/cmd/secrets-store-csi-driver/main.go#L55-L77), the AWS provider [no](https://github.com/aws/secrets-store-csi-driver-provider-aws/blob/main/main.go#L22-L25).

**Comment by fubar** [comment]
I'll try out the `logFormatJSON` option tomorrow, thanks!

**Comment by fubar** [comment]
I tried out the available options of the CSI driver, but they have no effect on the log level. Everything still gets logged as errors. Unfortunately, the only option we have is to not log anything the driver and provider are outputting.

**Comment by pierluigilenoci** [comment]
@fubar I quote myself. 

> Keep in mind that Klog (the library used for logging) is affected by a fairly serious bug regarding error levels. And I don't see any fixes on the horizon anytime soon.
> 
> Ref: [kubernetes/klog#212](https://github.com/kubernetes/klog/issues/212)

**Comment by simonmarty** [comment]
We're waiting on the kubernetes team to fix the `klog` issue mentioned. Feel free to reopen when the upstream issue has been addressed.
