### ISSUE TITLE
Question: On Premise Use

### ISSUE THREAD

**Issue by stbraley** [aws/secrets-store-csi-driver-provider-aws#80]
Do you have a sample deployment to use the driver in on On Premise Kubernetes cluster? Or does the cluster need to be hosted in AWS?

**Comment by simonmarty** [comment]
The deployment YAML should work on an on prem cluster, are you seeing issues?

**Comment by johnjeffers** [comment]
I'm trying to run it on a local kubernetes cluster (using Docker Desktop) and I get this error:

`failed to mount secrets store object content" err="rpc error: code = Unknown desc = failed to retrieve region from node. error Region not found`

Of course I'm not surprised it can't find a region, but I'd like to know how to work around this.
