### ISSUE TITLE
can two kubernetes secrets sync with a single secrets in secrets manager aws

### ISSUE THREAD

**Issue by upa-mihir07** [aws/secrets-store-csi-driver-provider-aws#81]
We're trying to create secrets via secrets-store-csi-driver and the provider is AWS.
What our requirement is to create two secrets with different name but the data is same inside those secrets. Can this be possible?? (Same namespace)

We're trying to do but only one secret is getting created. Other is not created.

We need to create both secrets having same data.

**Comment by upa-mihir07** [comment]
The data is coming from same secret in secrets-manager in aws for both.

**Comment by upa-mihir07** [comment]
@simonmarty

**Comment by simonmarty** [comment]
Could you share some more details about your use case? I'm having trouble understanding why you'd want two kubernetes secrets pointing to the same Secrets Manager secret.

Are you trying to get two different version IDs?

**Comment by upa-mihir07** [comment]
We have 2 services which are using same secret data. 
Lets say if one service gets deleted then along with it the associated secret will also be deleted, and it will impact the other service.

So we need two secrets like **Secret1** and **Secret2** for **service1** and **service2** respectively, and the data is coming from same secret **_SecretXYZ_** in Aws secret manager.

@simonmarty .

**Comment by upa-mihir07** [comment]
Hi @simonmarty @aramase , 

Just to confirm.
For now this is not allowed? Creating two secrets in kubernetes cluster with same Secrets Manager secret.

I have tried this but not able to create 2 secrets. Only one is getting created.

So am I doing something wrong or it is not allowed yet?

**Comment by simonmarty** [comment]
The issue you are facing is being looked into.

**Comment by upa-mihir07** [comment]
Hi guys, the issue has been resolved. We can do that, like creating two secrets in kubernetes cluster with same Secrets Manager secret. (using secrets-store-csi-driver).

I'm doing something wrong. Fixed it and it is working fine.

Thank you @simonmarty @aramase
